[global]
# Your Spotify account name.
username = "316cusgw7nhtsumlnw752txbnla4"

# Your Spotify account password.
password = "xxx"

bitrate = 320
volume_normalisation = false
initial_volume = "100"
autoplay = true
