monitor = eDP-1, 1920x1080@60, 1920x1080, 1

env = QT_QPA_PLATFORM,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

exec-once = [workspace 1] firefox
exec-once = [workspace 2] kitty -e tmux new -As main
exec-once = hypridle >> ~/.cache/hypridle.log 2>&1
exec-once = dunst
exec-once = swww-daemon
exec-once = gammastep
exec-once = waybar
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist -max-items 5000 store
exec-once = wl-paste --type image --watch cliphist -max-items 5000 store
exec-once = kdeconnectd
# exec-once = hyprpm reload

source = ~/.dotfiles/hypr/hyprbinds.conf

debug {
  disable_logs = true
  enable_stdout_logs = true
}

input {
  kb_layout  = us
  kb_variant =
  kb_model   =
  kb_options = caps:escape # NOTE: Remap CAPSLOCK --> ESCAPE
  kb_rules   =
  follow_mouse = 1
  numlock_by_default = false
  sensitivity = 0

  touchpad {
    natural_scroll = no
    disable_while_typing = true
    scroll_factor = 1.6
  }
}

general {
  gaps_in = 3
  gaps_out = 6
  border_size = 0
  layout = dwindle
  allow_tearing = false
}

decoration {
  rounding = 1
  dim_inactive = 1
  dim_strength = 0.2

  blur {
    enabled = false
  }

  shadow {
    enabled = false
  }
}

animations {
  enabled = no
}

dwindle {
  pseudotile     = yes
  preserve_split = yes
}


misc {
  force_default_wallpaper = 0
  mouse_move_enables_dpms = false
  key_press_enables_dpms = true
  disable_hyprland_logo = true
  disable_splash_rendering = true
  vfr = true
  allow_session_lock_restore = true
}

plugin {
  hyprexpo {
    columns = 3
    gap_size = 0
    bg_col = rgb(111111)
    workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1, meaning workspace=1 will stay at position=first always
    skip_empty = true
    gesture_distance = 300 # how far is the "max" for the gesture
  }
}

windowrule = idleinhibit focus, class:^(.*Spotify.*)$
windowrule = workspace 11, class:^(.*Spotify.*)$

windowrule = idleinhibit focus, class:^(.*firefox.*)$

windowrule = opacity 0.9, class:^(.*Code.*)$

windowrule = float, class:^(.*nm-connection-editor.*)$

windowrule = float, class:^(.*dragon.*)$
windowrule = pin, class:^(.*dragon.*)$

windowrule = float, class:^(.*org.kde.polkit-kde-authentication-agent-1.*)$
windowrule = center, class:^(.*org.kde.polkit-kde-authentication-agent-1.*)$

windowrule = float, class:^(.*org.gnome.clocks.*)$
windowrule = size 500 600, class:^(.*org.gnome.clocks.*)$
windowrule = center, class:^(.*org.gnome.clocks.*)$

windowrule = pin, class:^(.*showmethekey-gtk.*)$
windowrule = float, class:^(.*showmethekey-gtk.*)$
windowrule = size 30%, class:^(.*showmethekey-gtk.*)$
windowrule = center, class:^(.*showmethekey-gtk.*)$

windowrule = opacity 0.8, class:^(.*foot.*)$
windowrule = pin, class:^(.*foot.*)$
windowrule = float, class:^(.*foot.*)$
windowrule = center, class:^(.*foot.*)$

windowrule = float, class:^(.*com.example..*)$
windowrule = size 450 900, class:^(.*com.example..*)$
windowrule = move 1450 50, class:^(.*com.example..*)$
