# $LOCKER = hyprlock -q --no-fade-in
$LOCKER = hyprlock
# $LOCKER = $HOME/scripts/waylock.sh
# $LOCKER = $HOME/scripts/swaylock.sh
$BRIGHTNESS_LOW = 180 # 3 min
$LOCK_SCREEN = 300 # 5 min
$SCREEN_OFF = 600 # 10 min
# $BRIGHTNESS_LOW = 5
# $LOCK_SCREEN = 10
# $SCREEN_OFF = 20
$SUSPEND = 1200 # 20 min

general {
    # lock_cmd = pidof $LOCKER || $LOCKER       # avoid starting multiple hyprlock instances.
    # before_sleep_cmd = loginctl lock-session    # lock before suspend.
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock --no-fade-in --immediate
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
    inhibit_sleep = 3
}

listener {
    timeout = $BRIGHTNESS_LOW
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = $LOCK_SCREEN
    on-timeout = $LOCKER
}

listener {
    timeout = $SCREEN_OFF
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = $SUSPEND
    on-timeout = systemctl suspend
}
