# import = ["~/.config/alacritty/themes/ayu_dark.toml"]
general.import = ["~/.config/alacritty/themes/vscode-dark.toml"]

# for windows config file in appdata/roaming/alacritty/alacritty.toml, add this. rest the same
# import = ["C:\\Users\\USER\\AppData\\Roaming\\alacritty\\xterm.toml"]
# [shell]
# program = "wsl"

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.2
# offset.x = 0  # For letter spacing (default: 0)
# offset.y = 4  # For line spacing (default: 0)

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "Liga SFMono Nerd Font"
# family = "SFMono"
style = "Regular"
# style = "Bold"


[font.italic]
family = "JetBrainsMono Nerd Font"
# family = "SF Mono"
style = "Italic"

# [font.bold_italic]
# family = "JetBrainsMono Nerd Font"
# style = "Bold Italic"

# [font.bold]
# family = "JetBrainsMono Nerd Font"
# style = "Bold"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "i"
mods = "Control"

[scrolling]
history = 100000
multiplier = 3

# [shell]
# program = "/usr/bin/zsh"

[selection]
save_to_clipboard = true

[cursor]
vi_mode_style = "Block" 

# [window]
# decorations = "none"
# dynamic_padding = false
# startup_mode = "Windowed"

[window.padding]
x = 1
y = 0
