# --- prefix change ---
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# --- fixes ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

tmux_conf_copy_to_os_clipboard=true
set -g mouse on
set -g status-position top
set -sg escape-time 10 # remove delay for exiting insert mode with ESC in Neovim

# --- keybindings ---
# panes
bind-key -n M-p confirm-before kill-pane
bind-key -n C-M-p confirm-before kill-window
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# windows
bind c new-window -c '#{pane_current_path}'
bind-key -n C-M-n new-window
bind -n S-Left  previous-window
bind -n S-Right next-window
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1
bind-key -n M-h split-window -c "#{pane_current_path}"
bind-key -n M-v split-window -h -c "#{pane_current_path}"
#bind k split-window -h
#bind m split-window -v


# --- plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin '27medkamal/tmux-session-wizard'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'schasse/tmux-jump'
set -g @plugin 'feqzz/tmux-spotify-info'

#set -g @plugin 'whame/tmux-modal'
#set -g @plugin 'catppuccin/tmux'
#set -g @plugin 'egel/tmux-gruvbox'

# NOTE: Press prefix + I (capital i, as in Install) to fetch the plugin.
# NOTE: Press prefix + alt + u (lowercase u as in uninstall) to remove the plugin.


# --- plugins config ---



# --- status line ---
set -g status on
set -g status-interval 1
set -g status-justify centre
set -g status-style fg=white,bg=#181818

# Highlight the current window.
setw -g window-status-current-style fg=colour16,bg=colour11,bright

# LEFT STATUS
set -g status-left-length 100
set -g status-left-style default
set -g status-left "\
#[fg=colour197, bg=#181818] #h \
#[fg=colour47, bg=#181818] #(ip addr | grep -e 'state UP' -A 2 | awk '/inet /{printf $2}') \
#[fg=colour9, bg=#181818] #(sensors -f | awk '/CPU/{printf $2}') \
#[fg=colour141, bg=#181818] #(free -m -h | awk '/Mem/{printf $3\"\/\"$2}') \
"

# RIGHT STATUS
set -g status-right-length 200
set -g status-right-style default
set -g status-right "\
#{spotify_info} \
#[fg=colour39, bg=#181818] #([ $(cat /sys/class/power_supply/AC/online) == 1 ] && printf '⚡️')#(cat /sys/class/power_supply/BAT0/capacity)%	 \
#[fg=colour215, bg=#181818]#(date +'%H:%M %-d-%b-%y')\
"

# restore
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'


# --- plugins keybindings ---
TMUX_FZF_LAUNCH_KEY="f"
set -g @session-wizard 'T'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$DOTFILES/tmux/plugins/tpm/tpm'