# --- prefix change ---
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix


# --- fixes ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

tmux_conf_copy_to_os_clipboard=true
set -g mouse on
set -g status-position top
set -sg escape-time 10 # remove delay for exiting insert mode with ESC in Neovim

# --- tweaks ---
tmux_conf_theme_prefix=""

# --- keybindings ---
# panes
bind-key -n M-p confirm-before kill-pane
bind-key -n C-M-p confirm-before kill-window
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# windows
bind c new-window -c '#{pane_current_path}'
bind-key -n C-M-n new-window
bind -n S-Left  previous-window
bind -n S-Right next-window
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1
bind-key -n M-h split-window -c "#{pane_current_path}"
bind-key -n M-v split-window -h -c "#{pane_current_path}"
#bind k split-window -h
#bind m split-window -v


# --- plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin '27medkamal/tmux-session-wizard'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-battery'
#set -g @plugin 'whame/tmux-modal'
set -g @plugin 'schasse/tmux-jump'

# NOTE: Press prefix + I (capital i, as in Install) to fetch the plugin.
# NOTE: Press prefix + alt + u (lowercase u as in uninstall) to remove the plugin.
# https://github.com/tmux-plugins/list
# https://github.com/rothgar/awesome-tmux#status-bar


# --- plugins config ---
# catppuccin
set -g @catppuccin_flavour 'mocha' # frappe, macchiato, latte, mocha
set -g @catppuccin_window_current_text "#{b:pane_current_path} *"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_right_separator "████████"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"

set -g @catppuccin_status_modules_right "session date_time battery"
set -g @catppuccin_date_time_text "%H:%M"
set -g @catppuccin_battery_text "#{battery_percentage} #{batt_color_charge_primary_tier6}"

# restore
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'


# --- plugins keybindings ---
TMUX_FZF_LAUNCH_KEY="f"
set -g @session-wizard 'T'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$DOTFILES/tmux/plugins/tpm/tpm'